### ISSUE TITLE
Add `osx-arm64` to the builds?

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/mariadb-connector-c-feedstock#17]
### Comment:

Is it feasible to update this feedstock for `osx-arm64`?

**Comment by avgra3** [comment]
It appears to be feasible to update the feedstock for `osx-arm64` . Original build did not include it due to it not being officially supported.

However, there appears to be a build from [homebrew](https://formulae.brew.sh/formula/mariadb-connector-c#default). I will be working on getting that built.

**Comment by darynwhite** [comment]
Installed for me, thanks!
